### ISSUE TITLE
systemless xposed conflicts

### ISSUE THREAD

**Issue by IceArms** [Nanolx/NanoMod#19]
Hello! Have a problem with your mod...
Systemless xposed doesn't work with NanoMod. After installing it, in Xposed Installer always have an orange colored exclamation mark, that notify "_Xposed Framework version 87.0 (Systemless by topjohnwu) is installed, but not active_".
After **un**installing NanoMod in Recovery, Xposed Installer shows everything is OK.
Also with standart installed microG apks (and additions), xposed works ok.
Device is Xiaomi Mi Max, ROM is **ResurrectionRemix-M-v5.7.4** for Hydrogen (https://forum.xda-developers.com/mi-max/development/rom6-0-1-resurrectionremix-m-v5-7-4-t3499140) (stable), **Magisk 12.0**, **NanoMod 9.1.20170607**, **xposed-v87.1-sdk23-topjohnwu** (_tried 87.0 too, but the same result_), **Material Design Xposed Installer** [29/04/17] by dvdandroid.
Have followed by all your intructions about installation. Also tried to install xposed for the first and then NanoMod, but result the same...
I've tried much things with order and other, but nothing helps...

Here's log from Xposed Installer:
06-10 22:45:53.241 I/Xposed  ( 3541): -----------------
06-10 22:45:53.241 I/Xposed  ( 3541): Starting Xposed version 87.0 (Systemless by topjohnwu), compiled for SDK 23
06-10 22:45:53.241 I/Xposed  ( 3541): Device: n/a (Xiaomi), Android version 6.0.1 (SDK 23)
06-10 22:45:53.241 I/Xposed  ( 3541): ROM: cm_hydrogen-userdebug 6.0.1 MOB31K 8061d169b1 test-keys
06-10 22:45:53.241 I/Xposed  ( 3541): Build fingerprint: n/a
06-10 22:45:53.241 I/Xposed  ( 3541): Platform: arm64-v8a, 64-bit binary, system server: yes
06-10 22:45:53.241 I/Xposed  ( 3541): SELinux enabled: yes, enforcing: no
06-10 22:45:56.027 I/Xposed  ( 3541): -----------------
06-10 22:45:56.027 I/Xposed  ( 3541): Added Xposed (/magisk/xposed/system/framework/XposedBridge.jar) to CLASSPATH
06-10 22:45:56.854 I/Xposed  ( 3541): Detected ART runtime
06-10 22:45:56.855 E/Xposed  ( 3541): Could not load libxposed: dlopen failed: cannot locate symbol "_ZN3art9ArtMethod22xposed_callback_methodE" referenced by "/magisk/xposed/system/lib64/libxposed_art.so"...
06-10 22:45:56.960 E/Xposed  ( 3541): Errors during Xposed initialization
06-10 22:45:56.960 E/Xposed  ( 3541): java.lang.UnsatisfiedLinkError: No implementation found for boolean de.robv.android.xposed.XposedBridge.hadInitErrors() (tried Java_de_robv_android_xposed_XposedBridge_hadInitErrors and Java_de_robv_android_xposed_XposedBridge_hadInitErrors__)
06-10 22:45:56.960 E/Xposed  ( 3541): 	at de.robv.android.xposed.XposedBridge.hadInitErrors(Native Method)
06-10 22:45:56.960 E/Xposed  ( 3541): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:77)
06-10 22:46:02.952 I/Xposed  ( 3542): -----------------
06-10 22:46:02.952 I/Xposed  ( 3542): Starting Xposed version 87.0 (Systemless by topjohnwu), compiled for SDK 23
06-10 22:46:02.952 I/Xposed  ( 3542): Device: n/a (Xiaomi), Android version 6.0.1 (SDK 23)
06-10 22:46:02.952 I/Xposed  ( 3542): ROM: cm_hydrogen-userdebug 6.0.1 MOB31K 8061d169b1 test-keys
06-10 22:46:02.952 I/Xposed  ( 3542): Build fingerprint: n/a
06-10 22:46:02.952 I/Xposed  ( 3542): Platform: arm64-v8a, 32-bit binary, system server: no
06-10 22:46:02.952 I/Xposed  ( 3542): SELinux enabled: yes, enforcing: no
06-10 22:46:05.755 I/Xposed  ( 3542): -----------------
06-10 22:46:05.755 I/Xposed  ( 3542): Added Xposed (/magisk/xposed/system/framework/XposedBridge.jar) to CLASSPATH
06-10 22:46:06.432 I/Xposed  ( 3542): Detected ART runtime
06-10 22:46:06.435 E/Xposed  ( 3542): Could not load libxposed: dlopen failed: cannot locate symbol "_ZN3art9ArtMethod21xposed_callback_classE" referenced by "/magisk/xposed/system/lib/libxposed_art.so"...
06-10 22:46:06.508 E/Xposed  ( 3542): Errors during Xposed initialization
06-10 22:46:06.508 E/Xposed  ( 3542): java.lang.UnsatisfiedLinkError: No implementation found for boolean de.robv.android.xposed.XposedBridge.hadInitErrors() (tried Java_de_robv_android_xposed_XposedBridge_hadInitErrors and Java_de_robv_android_xposed_XposedBridge_hadInitErrors__)
06-10 22:46:06.508 E/Xposed  ( 3542): 	at de.robv.android.xposed.XposedBridge.hadInitErrors(Native Method)
06-10 22:46:06.508 E/Xposed  ( 3542): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:77)
06-10 22:46:27.587 E/XposedInstaller( 7037): AdvancedInstallerFragment -> Unable to resolve host "raw.githubusercontent.com": No address associated with hostname

**Comment by IceArms** [comment]
Today tried this combination (NanoMod + sysless xposed) on Mokee (stable "history" release) based on Android 6.0.1. And it was even worse.
ROM > kernel (compatible) > Magisk > NanoMod > boot (ok) > patcher > xposed-topjohnwu > bootloop
ROM > kernel > Magisk > NanoMod > boot (ok) > patcher > boot (ok) > xposed-topjohnwu > bootloop
ROM > kernel > Magisk > xposed-topjohnwu > boot (ok) > NanoMod > patcher > bootloop

**Comment by Nanolx** [comment]
Thanks for your logs (and those posted over at XDA).

I'll have a look at what might cause it, but I first have to find some time (and downgrade one of my devices back to Marshmallow). So this might take a few days.

**Comment by Nanolx** [comment]
I downgraded my Tablet to Dirty Unicorns 6.0.1 and everything is working fine with:

* NanoMod 9.2 (and 9.3 beta1)
* xposed by topjohnwu
* Magisk v13 (official beta)
* Xposed Installer 2017/04/29

in your case it complains about that xposed library can't be loaded. I once had this issue on a TouchWiz ROM, too, but it's so long ago, I don't remember the solution anymore.

Either way I suggest that you update both NanoMod and Magisk to the mentioned versions. NanoMod 9.2 introduced additional bugfixes and Magisk v13 also changed many things internally.

**Comment by IceArms** [comment]
**Nanolx**, thank you very much! I'll try it!
Some additional thoughts about that bug - it happened not only to me, but a few people from the 4pda forum too (other devices). So I think it depends not so much on a particular system as on the interaction of components (as you wrote earlier, likely it was Magisk). In any case, I'll try at first new versions of those and write how it went.

**Comment by Nanolx** [comment]
Any news?

**Comment by IceArms** [comment]
Thank you for your interest! Unfortunately, there were no time to check (and needed device in working condition.)... But I'll definitely try in the coming days.
